# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e61573c145a4fc14086a41da219b1f9b9ca29b5dbaf0e93f22920f48ba86fc7d0ea238e2ffeeca842c6ef9dba2c1f571a324422c0f81f3f1b03f1195d48ded33

test:
  secret_key_base: 965e32ee9001e62f77af92d734de3c5b7919f4cf3ccc67f6fe1a1472543c218dbc1171911d409d42c44203d69734036b92a0ef0c0ea2d3db0e6faba4af764144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
